name: second_task_data_usage
description: Second task. Data usage

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.7.0
  intl: ^0.18.0
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  drift: ^2.6.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: 1.8.2
  cloud_firestore: ^4.5.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.3
  flutter_svg: ^2.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.6.0
  build_runner: ^2.3.3


flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700