// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7aM45CLo_1-yd03XT3dlApFSWvZa7Kkg',
    appId: '1:265484207469:android:ea2bfcaf8d47c817548664',
    messagingSenderId: '265484207469',
    projectId: 'secondtaskdatausage',
    databaseURL: 'https://secondtaskdatausage-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'secondtaskdatausage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUZR24AKDpYMNiwrPWt-w7YuPy--vEFT8',
    appId: '1:265484207469:ios:02f63d6f7593690f548664',
    messagingSenderId: '265484207469',
    projectId: 'secondtaskdatausage',
    databaseURL: 'https://secondtaskdatausage-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'secondtaskdatausage.appspot.com',
    iosClientId: '265484207469-5ljq0ugicvaggl6r00vsbbh6d4td03kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondTaskDataUsage',
  );
}
